apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: webhook
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: webhook
  name: mutating-webhook-configuration
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: mutating-webhook-configuration
      namespace: default
      path: /mutate-meta-github-com-v1-metawebhook
  failurePolicy: Fail
  name: mmetawebhook.kb.io
  rules:
  - apiGroups:
    - meta.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metawebhooks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: mutating-webhook-configuration
      namespace: default
      path: /validate-meta-github-com-v1-metawebhook
  failurePolicy: Fail
  name: vmetawebhook.kb.io
  rules:
  - apiGroups:
    - meta.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metawebhooks
  sideEffects: None
