FROM harbor.4pd.io/openaios/alpine:3.15.0
# Build the manager binary
ARG TARGETOS

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
WORKDIR /
COPY webhook-amd64 /webhook


USER 65532:65532

ENTRYPOINT ["/webhook"]
