apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIRENDQWdTZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFmTVIwd0d3WURWUVFERXhSelpXeG0KTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qRXhNRGN4TXpReE16aGFGdzB6TWpFeE1EUXhNelF4TXpoYQpNQjh4SFRBYkJnTlZCQU1URkhObGJHWXRjMmxuYm1Wa0xXczRjeTFqWlhKME1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZRZjU2UmdIZzV1UDJiTndDSVdQUVBJYkJqRXluTStrd1pQd1p0c1MKVDcvYUZGYVFGL3M4WEpZdm8relBXUUFsOTlndGg2UGw5djRpeERIank5bmhKdHNBSnI2YjRySkZscHBxVm54MgpGODNmUGtGaWdjeHo4by9tbUVLZzVvNlN0S3g1NWkrK3Z1MmlDaGNJRkd5bUZ2c2YzM2JRYlhpVEtkaVdiWkxkCnc1dk1LRHFRNXdNRWtadlZuNyt4dko0ZTRhTTQ3OGh0L21qRC9aN2tqL3ZpSlhGWnlWSG9lMUhPa1FvQ1JrUmIKdGE2R3VsODVzS2lndzRRelFIajJnSnFZT3FnT3AwZ0oySUdVWStTaGVEdlg1VXhpK0FhdVYvYXM0OXNNK2NidgpmZStxWmkxZjJtb0JlMGFzTkpzSHlmYjkrbENPekxvTnd1b1p1cU1iYlJNZlZRSURBUUFCbzJNd1lUQU9CZ05WCkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVMSVVhL3kyQnF0SEUKQ0R6VnphRmcyTnI5QWxRd0h3WURWUjBSQkJnd0ZvSVVjMlZzWmkxemFXZHVaV1F0YXpoekxXTmxjblF3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCY09PTUZKbDF5a2ZrNk44ZU9BU3pVeEtGelZ3dXBLT3VWQlV3WTVXbkc2CnJkeWRpZkNZNnN1WFh4alVuZWxXZlVoSWh2SmJDYkQ4WUpoNWxNbUVaaXZwaVQvRTIvR2NkRHlpdlAxQkZLTnoKNWxrZHFlTVlwTHpQc3FlQXVmNU1uenEydWkxVG9ZUUFubURIcHBYeGZDczZCWDJ5K1Z0MlR5Mi9majZzSk1yegpucUNUOURHWXY4bUhiSk5lVEp6Vy9SdzlrQTBzeWxGemxhN0psV3hwblhaNStXbThuRXN0NmR2SnFRdVhDUFcrCjd5U0xLT0RFOXVUMkxLR2lnTEJUb3V6d2lNaVFpeFc3WE84TnNzQXZGNFdrdkNlK0tVY1IvbG1RcStXRW9XQmgKNTZKWEp4M2RqOTBXa1hHOXRidmtFU0V1eTFzdEdIbTJjRnVpSWJQL3htWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: default
      path: /mutate-meta-github-com-v1-metawebhook
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mmetawebhook.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - meta.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metawebhooks
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
